[build]
builder = "dockerfile"

[deploy]
startCommand = "python server_with_save.py --server-address 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
